wordpress:
    image: wordpress
    links:
        - db:mysql
    ports:
        - 8080:80

db:
    image: mariadb
    environment:
        MYSQL_ROOT_PASSWORD: example

data:
    image: mariadb
    volumes_from:
        - wordpress
        - db
    entrypoint: echo
    command: "data-only container for wordpress"
